### PR TITLE
chore(packages): set npm/yarn/pnpm versions

### PR DESCRIPTION
**Pull request by enzonotario**
It sets the engine versions for all packages, to be able to install it in environments like StackBlitz:

image

### CODE REVIEW

**Comment by enzonotario** [comment]
@aralroca previously I've added this changes only for `brisa` package, but then I noticed you changed these lines in the PR #562 (https://github.com/brisa-build/brisa/pull/562/files#diff-fa31e6b7191dd6fb715074c8b331c912df26fd6cca2c4dc9510a5742ac2faca7R144),

Was it intentional? I'm trying to add it again, this time for all packages, to be able to run it in StackBlitz.

However, so far I can't get it working with preview packages:

https://stackblitz.com/edit/stackblitz-starters-pq3bzs?file=package.json

**Comment by aralroca** [comment]
@enzonotario the problems comes on this script to update Bun version:

https://github.com/brisa-build/brisa/blob/5b35d868cbcb8aec28f9b8fdefe17eb3c924c7d6/scripts/upgrade-bun.ts#L34

You probably need to change it here, otherwise is updating the packages after running `bun run upgrade` (what this commit did it).

**Comment by enzonotario** [comment]
Nice! Now I understand. It's fixed now, and I've ran `upgrade-bun`. Thanks!

**Review by aralroca — APPROVED** [review]
Thanks @enzonotario

**Pull request merged**
